services:
  app:
    image: registry.digitalocean.com/patina/patina-test
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_DB
      - DATABASE_USER
      - DATABASE_PASSWORD
      - PATINA_ADMIN_PASSWORD
      - PATINA_ADMIN_COOKIE
