services:
  app:
    image: patina-test
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_DB
      - DATABASE_USER
      - DATABASE_PASSWORD
