name: build-image
run-name: building image on ${{ github.actor }}'s commits
on:
  push:
    branches:
      - main
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install Docker CLI
        run: sudo apt-get update && sudo apt-get install -y docker.io

      - name: Log in to DigitalOcean Container Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DO_DOCKER_IMAGE_UPLOAD_PAT }}
          DOCKER_PASSWORD: ${{ secrets.DO_DOCKER_IMAGE_UPLOAD_PAT }}
        run: echo $DOCKER_PASSWORD | docker login registry.digitalocean.com -u $DOCKER_USERNAME --password-stdin

      - name: Build and push Docker image
        env:
          DO_DOCKER_IMAGE_UPLOAD_PAT: ${{ secrets.DO_DOCKER_IMAGE_UPLOAD_PAT }}
        run: ./gradlew bootBuildImage
