name: example-action
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
      - run: |
          pnpm run test
