name: example-action
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - working-directory: ./js
        run: |
          pnpm install
          pnpm run test
      - working-directory: ./.github/workflows
        run: |
          curl -u aruan20:meaVEjM1P88Aiszpd3SaA2jyHTLDXm4kjQwK6czo7Q -X POST -H "Content-Type: application/json" --data @file.json https://gerrithub.io/a/changes/Ia101a1d27b20c1466e0b674ba7fd333b7d16a47f/revisions/current/review
