name: example-action
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - working-directory: ./.github/workflows
        run: |
          curl -u aruan20:meaVEjM1P88Aiszpd3SaA2jyHTLDXm4kjQwK6czo7Q -X POST -H "Content-Type: application/json" --data @file.json https://gerrithub.io/a/changes/I2c08060a80cc76ab8da2cc15e637079728b1723b/revisions/current/review
