name: test-action
run-name: ${{ github.actor }} is testing stuff
on:
  workflow_dispatch:
    inputs:
      testInput:
        description: 'a test input'
        required: true
        default: 'ooo'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "a"
          echo "hiiiiii"
          echo "modifications . .. . .. ... "
          echo "TestInput: ${{ github.event.inputs.testInput }}"
